package:
  name: snakepipes
  version: 1.3.0

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3
  run:
    - python >=3
    - snakemake >=5.2.3
    - pandas
    - graphviz
    - fuzzywuzzy
    - pyyaml >=5.1

test:
  commands:
    - DNA-mapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: MIT
  summary: NGS processing pipelines from the MPI-IE
  license_file: LICENSE
