## Please comment out and adjust configuration variables if their default values are
## not appropriate for your input data

## paired-end read name extension
# reads: ["_R1", "_R2"]

## FASTQ file extension
# ext: ".fastq.gz"

## Mate orientation in paired-end experiments (default is for Illumina sequencing)
# mate_orientation: "--fr"

## Median/mean fragment length
# fragment_length: 200

## Options to TrimGalore
# trim_galore_opts: "--stringency 2"


## The following configuration variables can only be set via this configuration
## file when calling snakemake directly, i.e. without using the wrapper script
## DNA-mapping.
## example call: snakemake --snakefile snakemake_workflows/workflows/DNA-mapping/Snakefile
##                         --cores 32
##                         --configfile snakemake_workflows/workflows/DNA-mapping/example.config.yaml
##                         --directory output-dir
# maindir: /home/arichter/projects/snakemake/snakemake_workflows/
# indir: /rapidus/data/arichter/snakemake_test/51_Hf12_SFTR_RD_run1/input/
# genome: hs37d5
# downsample: 50000
# trim: True
# fastqc: True
# bw_binsize: 10
