## Please comment out and adjust configuration variables if their default values are
## not appropriate for your input data

## Median/mean fragment length
# fragment_length: 200


## The following configuration variables can only be set via this configuration
## file when calling snakemake directly, i.e. without using the wrapper script
## DNA-mapping.
## example call: snakemake --snakefile snakemake_workflows/workflows/DNA-mapping/Snakefile
##                         --cores 32
##                         --configfile snakemake_workflows/workflows/DNA-mapping/example.config.yaml
##                         --directory output-dir
maindir: /home/arichter/projects/snakemake/snakemake_workflows/
indir: /rapidus/data/arichter/snakemake_test/51_Hf12_SFTR_RD_run1/output/
genome: hs37d5
chip_dict:
  51_Hf12_SFTR_RD_H3K27ac_F:
    control: 51_Hf12_SFTR_RD_Input_F
    broad: True
#  51_Hf12_SFTR_RD_H3K27me_F:
#    control: False
#    broad: False
paired: True
fragment_length: 200
# bw_binsize: 10


# verbose: True
